# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-13 12:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Filter',
        ),
    ]
